//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OztekSmsWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:OztekSmsWebService", ConfigurationName="OztekSmsWebService.OztekSmsWebServicePortType")]
    internal interface OztekSmsWebServicePortType
    {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:TekSmsiBirdenCokNumarayaGonder) of message TekSmsiBirdenCokNumarayaGonderRequest does not match the default value (urn:OztekSmsWebService)
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#TekSmsiBirdenCokNumarayaGonder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OztekSmsWebService.TekSmsiBirdenCokNumarayaGonderResponse TekSmsiBirdenCokNumarayaGonder(OztekSmsWebService.TekSmsiBirdenCokNumarayaGonderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#TekSmsiBirdenCokNumarayaGonder", ReplyAction="*")]
        System.Threading.Tasks.Task<OztekSmsWebService.TekSmsiBirdenCokNumarayaGonderResponse> TekSmsiBirdenCokNumarayaGonderAsync(OztekSmsWebService.TekSmsiBirdenCokNumarayaGonderRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:HerBirNumarayaFarkliSmsGonder) of message HerBirNumarayaFarkliSmsGonderRequest does not match the default value (urn:OztekSmsWebService)
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#HerBirNumarayaFarkliSmsGonder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OztekSmsWebService.HerBirNumarayaFarkliSmsGonderResponse HerBirNumarayaFarkliSmsGonder(OztekSmsWebService.HerBirNumarayaFarkliSmsGonderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#HerBirNumarayaFarkliSmsGonder", ReplyAction="*")]
        System.Threading.Tasks.Task<OztekSmsWebService.HerBirNumarayaFarkliSmsGonderResponse> HerBirNumarayaFarkliSmsGonderAsync(OztekSmsWebService.HerBirNumarayaFarkliSmsGonderRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:Smsiptalet) of message SmsiptaletRequest does not match the default value (urn:OztekSmsWebService)
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#Smsiptalet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OztekSmsWebService.SmsiptaletResponse Smsiptalet(OztekSmsWebService.SmsiptaletRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#Smsiptalet", ReplyAction="*")]
        System.Threading.Tasks.Task<OztekSmsWebService.SmsiptaletResponse> SmsiptaletAsync(OztekSmsWebService.SmsiptaletRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:OrjinatorGonder) of message OrjinatorGonderRequest does not match the default value (urn:OztekSmsWebService)
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#OrjinatorGonder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OztekSmsWebService.OrjinatorGonderResponse OrjinatorGonder(OztekSmsWebService.OrjinatorGonderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#OrjinatorGonder", ReplyAction="*")]
        System.Threading.Tasks.Task<OztekSmsWebService.OrjinatorGonderResponse> OrjinatorGonderAsync(OztekSmsWebService.OrjinatorGonderRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:RaporSorgula) of message RaporSorgulaRequest does not match the default value (urn:OztekSmsWebService)
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#RaporSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OztekSmsWebService.RaporSorgulaResponse RaporSorgula(OztekSmsWebService.RaporSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#RaporSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<OztekSmsWebService.RaporSorgulaResponse> RaporSorgulaAsync(OztekSmsWebService.RaporSorgulaRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:UyeBilgisiSorgula) of message UyeBilgisiSorgulaRequest does not match the default value (urn:OztekSmsWebService)
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#UyeBilgisiSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OztekSmsWebService.UyeBilgisiSorgulaResponse UyeBilgisiSorgula(OztekSmsWebService.UyeBilgisiSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#UyeBilgisiSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<OztekSmsWebService.UyeBilgisiSorgulaResponse> UyeBilgisiSorgulaAsync(OztekSmsWebService.UyeBilgisiSorgulaRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:OrjinatorSorgula) of message OrjinatorSorgulaRequest does not match the default value (urn:OztekSmsWebService)
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#OrjinatorSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OztekSmsWebService.OrjinatorSorgulaResponse OrjinatorSorgula(OztekSmsWebService.OrjinatorSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#OrjinatorSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<OztekSmsWebService.OrjinatorSorgulaResponse> OrjinatorSorgulaAsync(OztekSmsWebService.OrjinatorSorgulaRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:GunlukRaporSorgula) of message GunlukRaporSorgulaRequest does not match the default value (urn:OztekSmsWebService)
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#GunlukRaporSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OztekSmsWebService.GunlukRaporSorgulaResponse GunlukRaporSorgula(OztekSmsWebService.GunlukRaporSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#GunlukRaporSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<OztekSmsWebService.GunlukRaporSorgulaResponse> GunlukRaporSorgulaAsync(OztekSmsWebService.GunlukRaporSorgulaRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:ikitariharasisorgulaXMLver) of message ikitariharasisorgulaXMLverRequest does not match the default value (urn:OztekSmsWebService)
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#ikitariharasisorgulaXMLver", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OztekSmsWebService.ikitariharasisorgulaXMLverResponse ikitariharasisorgulaXMLver(OztekSmsWebService.ikitariharasisorgulaXMLverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#ikitariharasisorgulaXMLver", ReplyAction="*")]
        System.Threading.Tasks.Task<OztekSmsWebService.ikitariharasisorgulaXMLverResponse> ikitariharasisorgulaXMLverAsync(OztekSmsWebService.ikitariharasisorgulaXMLverRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:ikitariharasisorgulaXMLverID) of message ikitariharasisorgulaXMLverIDRequest does not match the default value (urn:OztekSmsWebService)
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#ikitariharasisorgulaXMLverID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OztekSmsWebService.ikitariharasisorgulaXMLverIDResponse ikitariharasisorgulaXMLverID(OztekSmsWebService.ikitariharasisorgulaXMLverIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#ikitariharasisorgulaXMLverID", ReplyAction="*")]
        System.Threading.Tasks.Task<OztekSmsWebService.ikitariharasisorgulaXMLverIDResponse> ikitariharasisorgulaXMLverIDAsync(OztekSmsWebService.ikitariharasisorgulaXMLverIDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:gelenSMSleriSorgula) of message gelenSMSleriSorgulaRequest does not match the default value (urn:OztekSmsWebService)
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#gelenSMSleriSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OztekSmsWebService.gelenSMSleriSorgulaResponse gelenSMSleriSorgula(OztekSmsWebService.gelenSMSleriSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:testnamespace#gelenSMSleriSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<OztekSmsWebService.gelenSMSleriSorgulaResponse> gelenSMSleriSorgulaAsync(OztekSmsWebService.gelenSMSleriSorgulaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TekSmsiBirdenCokNumarayaGonder", WrapperNamespace="urn:TekSmsiBirdenCokNumarayaGonder", IsWrapped=true)]
    internal partial class TekSmsiBirdenCokNumarayaGonderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string orjinator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string numaralar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string mesaj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string zaman;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string zamanasimi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string tip;
        
        public TekSmsiBirdenCokNumarayaGonderRequest()
        {
        }
        
        public TekSmsiBirdenCokNumarayaGonderRequest(string kullanicino, string kullaniciadi, string sifre, string orjinator, string numaralar, string mesaj, string zaman, string zamanasimi, string tip)
        {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
            this.orjinator = orjinator;
            this.numaralar = numaralar;
            this.mesaj = mesaj;
            this.zaman = zaman;
            this.zamanasimi = zamanasimi;
            this.tip = tip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TekSmsiBirdenCokNumarayaGonderResponse", WrapperNamespace="urn:TekSmsiBirdenCokNumarayaGonder", IsWrapped=true)]
    internal partial class TekSmsiBirdenCokNumarayaGonderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public TekSmsiBirdenCokNumarayaGonderResponse()
        {
        }
        
        public TekSmsiBirdenCokNumarayaGonderResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HerBirNumarayaFarkliSmsGonder", WrapperNamespace="urn:HerBirNumarayaFarkliSmsGonder", IsWrapped=true)]
    internal partial class HerBirNumarayaFarkliSmsGonderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string orjinator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string numaramesaj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string zaman;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string zamanasimi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string tip;
        
        public HerBirNumarayaFarkliSmsGonderRequest()
        {
        }
        
        public HerBirNumarayaFarkliSmsGonderRequest(string kullanicino, string kullaniciadi, string sifre, string orjinator, string numaramesaj, string zaman, string zamanasimi, string tip)
        {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
            this.orjinator = orjinator;
            this.numaramesaj = numaramesaj;
            this.zaman = zaman;
            this.zamanasimi = zamanasimi;
            this.tip = tip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HerBirNumarayaFarkliSmsGonderResponse", WrapperNamespace="urn:HerBirNumarayaFarkliSmsGonder", IsWrapped=true)]
    internal partial class HerBirNumarayaFarkliSmsGonderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public HerBirNumarayaFarkliSmsGonderResponse()
        {
        }
        
        public HerBirNumarayaFarkliSmsGonderResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Smsiptalet", WrapperNamespace="urn:Smsiptalet", IsWrapped=true)]
    internal partial class SmsiptaletRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ozelid;
        
        public SmsiptaletRequest()
        {
        }
        
        public SmsiptaletRequest(string kullanicino, string kullaniciadi, string sifre, string ozelid)
        {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
            this.ozelid = ozelid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmsiptaletResponse", WrapperNamespace="urn:Smsiptalet", IsWrapped=true)]
    internal partial class SmsiptaletResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SmsiptaletResponse()
        {
        }
        
        public SmsiptaletResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrjinatorGonder", WrapperNamespace="urn:OrjinatorGonder", IsWrapped=true)]
    internal partial class OrjinatorGonderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string orjinator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string aciklama;
        
        public OrjinatorGonderRequest()
        {
        }
        
        public OrjinatorGonderRequest(string kullanicino, string kullaniciadi, string sifre, string orjinator, string aciklama)
        {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
            this.orjinator = orjinator;
            this.aciklama = aciklama;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrjinatorGonderResponse", WrapperNamespace="urn:OrjinatorGonder", IsWrapped=true)]
    internal partial class OrjinatorGonderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public OrjinatorGonderResponse()
        {
        }
        
        public OrjinatorGonderResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RaporSorgula", WrapperNamespace="urn:RaporSorgula", IsWrapped=true)]
    internal partial class RaporSorgulaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ozelid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string numara;
        
        public RaporSorgulaRequest()
        {
        }
        
        public RaporSorgulaRequest(string kullanicino, string kullaniciadi, string sifre, string ozelid, string numara)
        {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
            this.ozelid = ozelid;
            this.numara = numara;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RaporSorgulaResponse", WrapperNamespace="urn:RaporSorgula", IsWrapped=true)]
    internal partial class RaporSorgulaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public RaporSorgulaResponse()
        {
        }
        
        public RaporSorgulaResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UyeBilgisiSorgula", WrapperNamespace="urn:UyeBilgisiSorgula", IsWrapped=true)]
    internal partial class UyeBilgisiSorgulaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        public UyeBilgisiSorgulaRequest()
        {
        }
        
        public UyeBilgisiSorgulaRequest(string kullanicino, string kullaniciadi, string sifre)
        {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UyeBilgisiSorgulaResponse", WrapperNamespace="urn:UyeBilgisiSorgula", IsWrapped=true)]
    internal partial class UyeBilgisiSorgulaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public UyeBilgisiSorgulaResponse()
        {
        }
        
        public UyeBilgisiSorgulaResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrjinatorSorgula", WrapperNamespace="urn:OrjinatorSorgula", IsWrapped=true)]
    internal partial class OrjinatorSorgulaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string orjinator;
        
        public OrjinatorSorgulaRequest()
        {
        }
        
        public OrjinatorSorgulaRequest(string kullanicino, string kullaniciadi, string sifre, string orjinator)
        {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
            this.orjinator = orjinator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrjinatorSorgulaResponse", WrapperNamespace="urn:OrjinatorSorgula", IsWrapped=true)]
    internal partial class OrjinatorSorgulaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public OrjinatorSorgulaResponse()
        {
        }
        
        public OrjinatorSorgulaResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GunlukRaporSorgula", WrapperNamespace="urn:GunlukRaporSorgula", IsWrapped=true)]
    internal partial class GunlukRaporSorgulaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string tarih;
        
        public GunlukRaporSorgulaRequest()
        {
        }
        
        public GunlukRaporSorgulaRequest(string kullanicino, string kullaniciadi, string sifre, string tarih)
        {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
            this.tarih = tarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GunlukRaporSorgulaResponse", WrapperNamespace="urn:GunlukRaporSorgula", IsWrapped=true)]
    internal partial class GunlukRaporSorgulaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GunlukRaporSorgulaResponse()
        {
        }
        
        public GunlukRaporSorgulaResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ikitariharasisorgulaXMLver", WrapperNamespace="urn:ikitariharasisorgulaXMLver", IsWrapped=true)]
    internal partial class ikitariharasisorgulaXMLverRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string baslangictarih;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string bitistarih;
        
        public ikitariharasisorgulaXMLverRequest()
        {
        }
        
        public ikitariharasisorgulaXMLverRequest(string kullanicino, string kullaniciadi, string sifre, string baslangictarih, string bitistarih)
        {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
            this.baslangictarih = baslangictarih;
            this.bitistarih = bitistarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ikitariharasisorgulaXMLverResponse", WrapperNamespace="urn:ikitariharasisorgulaXMLver", IsWrapped=true)]
    internal partial class ikitariharasisorgulaXMLverResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ikitariharasisorgulaXMLverResponse()
        {
        }
        
        public ikitariharasisorgulaXMLverResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ikitariharasisorgulaXMLverID", WrapperNamespace="urn:ikitariharasisorgulaXMLverID", IsWrapped=true)]
    internal partial class ikitariharasisorgulaXMLverIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string baslangictarih;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string bitistarih;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string smsid;
        
        public ikitariharasisorgulaXMLverIDRequest()
        {
        }
        
        public ikitariharasisorgulaXMLverIDRequest(string kullanicino, string kullaniciadi, string sifre, string baslangictarih, string bitistarih, string smsid)
        {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
            this.baslangictarih = baslangictarih;
            this.bitistarih = bitistarih;
            this.smsid = smsid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ikitariharasisorgulaXMLverIDResponse", WrapperNamespace="urn:ikitariharasisorgulaXMLverID", IsWrapped=true)]
    internal partial class ikitariharasisorgulaXMLverIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ikitariharasisorgulaXMLverIDResponse()
        {
        }
        
        public ikitariharasisorgulaXMLverIDResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gelenSMSleriSorgula", WrapperNamespace="urn:gelenSMSleriSorgula", IsWrapped=true)]
    internal partial class gelenSMSleriSorgulaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string kullanicino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string kullaniciadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string baslangictarih;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string bitistarih;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string durum;
        
        public gelenSMSleriSorgulaRequest()
        {
        }
        
        public gelenSMSleriSorgulaRequest(string kullanicino, string kullaniciadi, string sifre, string baslangictarih, string bitistarih, string durum)
        {
            this.kullanicino = kullanicino;
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
            this.baslangictarih = baslangictarih;
            this.bitistarih = bitistarih;
            this.durum = durum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gelenSMSleriSorgulaResponse", WrapperNamespace="urn:gelenSMSleriSorgula", IsWrapped=true)]
    internal partial class gelenSMSleriSorgulaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public gelenSMSleriSorgulaResponse()
        {
        }
        
        public gelenSMSleriSorgulaResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface OztekSmsWebServicePortTypeChannel : OztekSmsWebService.OztekSmsWebServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class OztekSmsWebServicePortTypeClient : System.ServiceModel.ClientBase<OztekSmsWebService.OztekSmsWebServicePortType>, OztekSmsWebService.OztekSmsWebServicePortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OztekSmsWebServicePortTypeClient() : 
                base(OztekSmsWebServicePortTypeClient.GetDefaultBinding(), OztekSmsWebServicePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.OztekSmsWebServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OztekSmsWebServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(OztekSmsWebServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), OztekSmsWebServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OztekSmsWebServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OztekSmsWebServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OztekSmsWebServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OztekSmsWebServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OztekSmsWebServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OztekSmsWebService.TekSmsiBirdenCokNumarayaGonderResponse OztekSmsWebService.OztekSmsWebServicePortType.TekSmsiBirdenCokNumarayaGonder(OztekSmsWebService.TekSmsiBirdenCokNumarayaGonderRequest request)
        {
            return base.Channel.TekSmsiBirdenCokNumarayaGonder(request);
        }
        
        public string TekSmsiBirdenCokNumarayaGonder(string kullanicino, string kullaniciadi, string sifre, string orjinator, string numaralar, string mesaj, string zaman, string zamanasimi, string tip)
        {
            OztekSmsWebService.TekSmsiBirdenCokNumarayaGonderRequest inValue = new OztekSmsWebService.TekSmsiBirdenCokNumarayaGonderRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.orjinator = orjinator;
            inValue.numaralar = numaralar;
            inValue.mesaj = mesaj;
            inValue.zaman = zaman;
            inValue.zamanasimi = zamanasimi;
            inValue.tip = tip;
            OztekSmsWebService.TekSmsiBirdenCokNumarayaGonderResponse retVal = ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).TekSmsiBirdenCokNumarayaGonder(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OztekSmsWebService.TekSmsiBirdenCokNumarayaGonderResponse> OztekSmsWebService.OztekSmsWebServicePortType.TekSmsiBirdenCokNumarayaGonderAsync(OztekSmsWebService.TekSmsiBirdenCokNumarayaGonderRequest request)
        {
            return base.Channel.TekSmsiBirdenCokNumarayaGonderAsync(request);
        }
        
        public System.Threading.Tasks.Task<OztekSmsWebService.TekSmsiBirdenCokNumarayaGonderResponse> TekSmsiBirdenCokNumarayaGonderAsync(string kullanicino, string kullaniciadi, string sifre, string orjinator, string numaralar, string mesaj, string zaman, string zamanasimi, string tip)
        {
            OztekSmsWebService.TekSmsiBirdenCokNumarayaGonderRequest inValue = new OztekSmsWebService.TekSmsiBirdenCokNumarayaGonderRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.orjinator = orjinator;
            inValue.numaralar = numaralar;
            inValue.mesaj = mesaj;
            inValue.zaman = zaman;
            inValue.zamanasimi = zamanasimi;
            inValue.tip = tip;
            return ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).TekSmsiBirdenCokNumarayaGonderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OztekSmsWebService.HerBirNumarayaFarkliSmsGonderResponse OztekSmsWebService.OztekSmsWebServicePortType.HerBirNumarayaFarkliSmsGonder(OztekSmsWebService.HerBirNumarayaFarkliSmsGonderRequest request)
        {
            return base.Channel.HerBirNumarayaFarkliSmsGonder(request);
        }
        
        public string HerBirNumarayaFarkliSmsGonder(string kullanicino, string kullaniciadi, string sifre, string orjinator, string numaramesaj, string zaman, string zamanasimi, string tip)
        {
            OztekSmsWebService.HerBirNumarayaFarkliSmsGonderRequest inValue = new OztekSmsWebService.HerBirNumarayaFarkliSmsGonderRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.orjinator = orjinator;
            inValue.numaramesaj = numaramesaj;
            inValue.zaman = zaman;
            inValue.zamanasimi = zamanasimi;
            inValue.tip = tip;
            OztekSmsWebService.HerBirNumarayaFarkliSmsGonderResponse retVal = ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).HerBirNumarayaFarkliSmsGonder(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OztekSmsWebService.HerBirNumarayaFarkliSmsGonderResponse> OztekSmsWebService.OztekSmsWebServicePortType.HerBirNumarayaFarkliSmsGonderAsync(OztekSmsWebService.HerBirNumarayaFarkliSmsGonderRequest request)
        {
            return base.Channel.HerBirNumarayaFarkliSmsGonderAsync(request);
        }
        
        public System.Threading.Tasks.Task<OztekSmsWebService.HerBirNumarayaFarkliSmsGonderResponse> HerBirNumarayaFarkliSmsGonderAsync(string kullanicino, string kullaniciadi, string sifre, string orjinator, string numaramesaj, string zaman, string zamanasimi, string tip)
        {
            OztekSmsWebService.HerBirNumarayaFarkliSmsGonderRequest inValue = new OztekSmsWebService.HerBirNumarayaFarkliSmsGonderRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.orjinator = orjinator;
            inValue.numaramesaj = numaramesaj;
            inValue.zaman = zaman;
            inValue.zamanasimi = zamanasimi;
            inValue.tip = tip;
            return ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).HerBirNumarayaFarkliSmsGonderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OztekSmsWebService.SmsiptaletResponse OztekSmsWebService.OztekSmsWebServicePortType.Smsiptalet(OztekSmsWebService.SmsiptaletRequest request)
        {
            return base.Channel.Smsiptalet(request);
        }
        
        public string Smsiptalet(string kullanicino, string kullaniciadi, string sifre, string ozelid)
        {
            OztekSmsWebService.SmsiptaletRequest inValue = new OztekSmsWebService.SmsiptaletRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.ozelid = ozelid;
            OztekSmsWebService.SmsiptaletResponse retVal = ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).Smsiptalet(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OztekSmsWebService.SmsiptaletResponse> OztekSmsWebService.OztekSmsWebServicePortType.SmsiptaletAsync(OztekSmsWebService.SmsiptaletRequest request)
        {
            return base.Channel.SmsiptaletAsync(request);
        }
        
        public System.Threading.Tasks.Task<OztekSmsWebService.SmsiptaletResponse> SmsiptaletAsync(string kullanicino, string kullaniciadi, string sifre, string ozelid)
        {
            OztekSmsWebService.SmsiptaletRequest inValue = new OztekSmsWebService.SmsiptaletRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.ozelid = ozelid;
            return ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).SmsiptaletAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OztekSmsWebService.OrjinatorGonderResponse OztekSmsWebService.OztekSmsWebServicePortType.OrjinatorGonder(OztekSmsWebService.OrjinatorGonderRequest request)
        {
            return base.Channel.OrjinatorGonder(request);
        }
        
        public string OrjinatorGonder(string kullanicino, string kullaniciadi, string sifre, string orjinator, string aciklama)
        {
            OztekSmsWebService.OrjinatorGonderRequest inValue = new OztekSmsWebService.OrjinatorGonderRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.orjinator = orjinator;
            inValue.aciklama = aciklama;
            OztekSmsWebService.OrjinatorGonderResponse retVal = ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).OrjinatorGonder(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OztekSmsWebService.OrjinatorGonderResponse> OztekSmsWebService.OztekSmsWebServicePortType.OrjinatorGonderAsync(OztekSmsWebService.OrjinatorGonderRequest request)
        {
            return base.Channel.OrjinatorGonderAsync(request);
        }
        
        public System.Threading.Tasks.Task<OztekSmsWebService.OrjinatorGonderResponse> OrjinatorGonderAsync(string kullanicino, string kullaniciadi, string sifre, string orjinator, string aciklama)
        {
            OztekSmsWebService.OrjinatorGonderRequest inValue = new OztekSmsWebService.OrjinatorGonderRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.orjinator = orjinator;
            inValue.aciklama = aciklama;
            return ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).OrjinatorGonderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OztekSmsWebService.RaporSorgulaResponse OztekSmsWebService.OztekSmsWebServicePortType.RaporSorgula(OztekSmsWebService.RaporSorgulaRequest request)
        {
            return base.Channel.RaporSorgula(request);
        }
        
        public string RaporSorgula(string kullanicino, string kullaniciadi, string sifre, string ozelid, string numara)
        {
            OztekSmsWebService.RaporSorgulaRequest inValue = new OztekSmsWebService.RaporSorgulaRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.ozelid = ozelid;
            inValue.numara = numara;
            OztekSmsWebService.RaporSorgulaResponse retVal = ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).RaporSorgula(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OztekSmsWebService.RaporSorgulaResponse> OztekSmsWebService.OztekSmsWebServicePortType.RaporSorgulaAsync(OztekSmsWebService.RaporSorgulaRequest request)
        {
            return base.Channel.RaporSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<OztekSmsWebService.RaporSorgulaResponse> RaporSorgulaAsync(string kullanicino, string kullaniciadi, string sifre, string ozelid, string numara)
        {
            OztekSmsWebService.RaporSorgulaRequest inValue = new OztekSmsWebService.RaporSorgulaRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.ozelid = ozelid;
            inValue.numara = numara;
            return ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).RaporSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OztekSmsWebService.UyeBilgisiSorgulaResponse OztekSmsWebService.OztekSmsWebServicePortType.UyeBilgisiSorgula(OztekSmsWebService.UyeBilgisiSorgulaRequest request)
        {
            return base.Channel.UyeBilgisiSorgula(request);
        }
        
        public string UyeBilgisiSorgula(string kullanicino, string kullaniciadi, string sifre)
        {
            OztekSmsWebService.UyeBilgisiSorgulaRequest inValue = new OztekSmsWebService.UyeBilgisiSorgulaRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            OztekSmsWebService.UyeBilgisiSorgulaResponse retVal = ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).UyeBilgisiSorgula(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OztekSmsWebService.UyeBilgisiSorgulaResponse> OztekSmsWebService.OztekSmsWebServicePortType.UyeBilgisiSorgulaAsync(OztekSmsWebService.UyeBilgisiSorgulaRequest request)
        {
            return base.Channel.UyeBilgisiSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<OztekSmsWebService.UyeBilgisiSorgulaResponse> UyeBilgisiSorgulaAsync(string kullanicino, string kullaniciadi, string sifre)
        {
            OztekSmsWebService.UyeBilgisiSorgulaRequest inValue = new OztekSmsWebService.UyeBilgisiSorgulaRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            return ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).UyeBilgisiSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OztekSmsWebService.OrjinatorSorgulaResponse OztekSmsWebService.OztekSmsWebServicePortType.OrjinatorSorgula(OztekSmsWebService.OrjinatorSorgulaRequest request)
        {
            return base.Channel.OrjinatorSorgula(request);
        }
        
        public string OrjinatorSorgula(string kullanicino, string kullaniciadi, string sifre, string orjinator)
        {
            OztekSmsWebService.OrjinatorSorgulaRequest inValue = new OztekSmsWebService.OrjinatorSorgulaRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.orjinator = orjinator;
            OztekSmsWebService.OrjinatorSorgulaResponse retVal = ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).OrjinatorSorgula(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OztekSmsWebService.OrjinatorSorgulaResponse> OztekSmsWebService.OztekSmsWebServicePortType.OrjinatorSorgulaAsync(OztekSmsWebService.OrjinatorSorgulaRequest request)
        {
            return base.Channel.OrjinatorSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<OztekSmsWebService.OrjinatorSorgulaResponse> OrjinatorSorgulaAsync(string kullanicino, string kullaniciadi, string sifre, string orjinator)
        {
            OztekSmsWebService.OrjinatorSorgulaRequest inValue = new OztekSmsWebService.OrjinatorSorgulaRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.orjinator = orjinator;
            return ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).OrjinatorSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OztekSmsWebService.GunlukRaporSorgulaResponse OztekSmsWebService.OztekSmsWebServicePortType.GunlukRaporSorgula(OztekSmsWebService.GunlukRaporSorgulaRequest request)
        {
            return base.Channel.GunlukRaporSorgula(request);
        }
        
        public string GunlukRaporSorgula(string kullanicino, string kullaniciadi, string sifre, string tarih)
        {
            OztekSmsWebService.GunlukRaporSorgulaRequest inValue = new OztekSmsWebService.GunlukRaporSorgulaRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.tarih = tarih;
            OztekSmsWebService.GunlukRaporSorgulaResponse retVal = ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).GunlukRaporSorgula(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OztekSmsWebService.GunlukRaporSorgulaResponse> OztekSmsWebService.OztekSmsWebServicePortType.GunlukRaporSorgulaAsync(OztekSmsWebService.GunlukRaporSorgulaRequest request)
        {
            return base.Channel.GunlukRaporSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<OztekSmsWebService.GunlukRaporSorgulaResponse> GunlukRaporSorgulaAsync(string kullanicino, string kullaniciadi, string sifre, string tarih)
        {
            OztekSmsWebService.GunlukRaporSorgulaRequest inValue = new OztekSmsWebService.GunlukRaporSorgulaRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.tarih = tarih;
            return ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).GunlukRaporSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OztekSmsWebService.ikitariharasisorgulaXMLverResponse OztekSmsWebService.OztekSmsWebServicePortType.ikitariharasisorgulaXMLver(OztekSmsWebService.ikitariharasisorgulaXMLverRequest request)
        {
            return base.Channel.ikitariharasisorgulaXMLver(request);
        }
        
        public string ikitariharasisorgulaXMLver(string kullanicino, string kullaniciadi, string sifre, string baslangictarih, string bitistarih)
        {
            OztekSmsWebService.ikitariharasisorgulaXMLverRequest inValue = new OztekSmsWebService.ikitariharasisorgulaXMLverRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.baslangictarih = baslangictarih;
            inValue.bitistarih = bitistarih;
            OztekSmsWebService.ikitariharasisorgulaXMLverResponse retVal = ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).ikitariharasisorgulaXMLver(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OztekSmsWebService.ikitariharasisorgulaXMLverResponse> OztekSmsWebService.OztekSmsWebServicePortType.ikitariharasisorgulaXMLverAsync(OztekSmsWebService.ikitariharasisorgulaXMLverRequest request)
        {
            return base.Channel.ikitariharasisorgulaXMLverAsync(request);
        }
        
        public System.Threading.Tasks.Task<OztekSmsWebService.ikitariharasisorgulaXMLverResponse> ikitariharasisorgulaXMLverAsync(string kullanicino, string kullaniciadi, string sifre, string baslangictarih, string bitistarih)
        {
            OztekSmsWebService.ikitariharasisorgulaXMLverRequest inValue = new OztekSmsWebService.ikitariharasisorgulaXMLverRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.baslangictarih = baslangictarih;
            inValue.bitistarih = bitistarih;
            return ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).ikitariharasisorgulaXMLverAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OztekSmsWebService.ikitariharasisorgulaXMLverIDResponse OztekSmsWebService.OztekSmsWebServicePortType.ikitariharasisorgulaXMLverID(OztekSmsWebService.ikitariharasisorgulaXMLverIDRequest request)
        {
            return base.Channel.ikitariharasisorgulaXMLverID(request);
        }
        
        public string ikitariharasisorgulaXMLverID(string kullanicino, string kullaniciadi, string sifre, string baslangictarih, string bitistarih, string smsid)
        {
            OztekSmsWebService.ikitariharasisorgulaXMLverIDRequest inValue = new OztekSmsWebService.ikitariharasisorgulaXMLverIDRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.baslangictarih = baslangictarih;
            inValue.bitistarih = bitistarih;
            inValue.smsid = smsid;
            OztekSmsWebService.ikitariharasisorgulaXMLverIDResponse retVal = ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).ikitariharasisorgulaXMLverID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OztekSmsWebService.ikitariharasisorgulaXMLverIDResponse> OztekSmsWebService.OztekSmsWebServicePortType.ikitariharasisorgulaXMLverIDAsync(OztekSmsWebService.ikitariharasisorgulaXMLverIDRequest request)
        {
            return base.Channel.ikitariharasisorgulaXMLverIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<OztekSmsWebService.ikitariharasisorgulaXMLverIDResponse> ikitariharasisorgulaXMLverIDAsync(string kullanicino, string kullaniciadi, string sifre, string baslangictarih, string bitistarih, string smsid)
        {
            OztekSmsWebService.ikitariharasisorgulaXMLverIDRequest inValue = new OztekSmsWebService.ikitariharasisorgulaXMLverIDRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.baslangictarih = baslangictarih;
            inValue.bitistarih = bitistarih;
            inValue.smsid = smsid;
            return ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).ikitariharasisorgulaXMLverIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OztekSmsWebService.gelenSMSleriSorgulaResponse OztekSmsWebService.OztekSmsWebServicePortType.gelenSMSleriSorgula(OztekSmsWebService.gelenSMSleriSorgulaRequest request)
        {
            return base.Channel.gelenSMSleriSorgula(request);
        }
        
        public string gelenSMSleriSorgula(string kullanicino, string kullaniciadi, string sifre, string baslangictarih, string bitistarih, string durum)
        {
            OztekSmsWebService.gelenSMSleriSorgulaRequest inValue = new OztekSmsWebService.gelenSMSleriSorgulaRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.baslangictarih = baslangictarih;
            inValue.bitistarih = bitistarih;
            inValue.durum = durum;
            OztekSmsWebService.gelenSMSleriSorgulaResponse retVal = ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).gelenSMSleriSorgula(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OztekSmsWebService.gelenSMSleriSorgulaResponse> OztekSmsWebService.OztekSmsWebServicePortType.gelenSMSleriSorgulaAsync(OztekSmsWebService.gelenSMSleriSorgulaRequest request)
        {
            return base.Channel.gelenSMSleriSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<OztekSmsWebService.gelenSMSleriSorgulaResponse> gelenSMSleriSorgulaAsync(string kullanicino, string kullaniciadi, string sifre, string baslangictarih, string bitistarih, string durum)
        {
            OztekSmsWebService.gelenSMSleriSorgulaRequest inValue = new OztekSmsWebService.gelenSMSleriSorgulaRequest();
            inValue.kullanicino = kullanicino;
            inValue.kullaniciadi = kullaniciadi;
            inValue.sifre = sifre;
            inValue.baslangictarih = baslangictarih;
            inValue.bitistarih = bitistarih;
            inValue.durum = durum;
            return ((OztekSmsWebService.OztekSmsWebServicePortType)(this)).gelenSMSleriSorgulaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OztekSmsWebServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OztekSmsWebServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://www.oztekbayi.com/webservis/service.php");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OztekSmsWebServicePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.OztekSmsWebServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OztekSmsWebServicePortTypeClient.GetEndpointAddress(EndpointConfiguration.OztekSmsWebServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            OztekSmsWebServicePort,
        }
    }
}
