export const RESET = "RESET"

export const SETTINGS_LAYOUT = 'SETTINGS_LAYOUT';
export const SETTINGS_MENUS = 'SETTINGS_MENUS';

export const SETTINGS_INIT_START = 'SETTINGS_INIT_START';
export const SETTINGS_INIT_SUCCESS = 'SETTINGS_INIT_SUCCESS';
export const SETTINGS_INIT_FAIL = 'SETTINGS_INIT_FAIL';

export const AUTH_GET_SETTINGS_START = 'AUTH_GET_SETTINGS_START';
export const AUTH_GET_SETTINGS_SUCCESS = 'AUTH_GET_SETTINGS_SUCCESS';
export const AUTH_GET_SETTINGS_FAIL = 'AUTH_GET_SETTINGS_FAIL';

export const AUTH_SAVE_SETTINGS_START = 'AUTH_SAVE_SETTINGS_START';
export const AUTH_SAVE_SETTINGS_SUCCESS = 'AUTH_SAVE_SETTINGS_SUCCESS';
export const AUTH_SAVE_SETTINGS_FAIL = 'AUTH_SAVE_SETTINGS_FAIL';
export const AUTH_SET_CURRENT_CONFIG = 'AUTH_SET_CURRENT_CONFIG';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const AUTH_REGISTER_START = 'AUTH_REGISTER_START';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAIL = 'AUTH_REGISTER_FAIL';

export const AUTH_CONFIRM_START = 'AUTH_CONFIRM_START';
export const AUTH_CONFIRM_SUCCESS = 'AUTH_CONFIRM_SUCCESS';
export const AUTH_CONFIRM_FAIL = 'AUTH_CONFIRM_FAIL';

export const AUTH_RECOVERY_START = 'AUTH_RECOVERY_START';
export const AUTH_RECOVERY_SUCCESS = 'AUTH_RECOVERY_SUCCESS';
export const AUTH_RECOVERY_FAIL = 'AUTH_RECOVERY_FAIL';

export const AUTH_CHANGE_PASSWORD_START = 'AUTH_CHANGE_PASSWORD_START';
export const AUTH_CHANGE_PASSWORD_SUCCESS = 'AUTH_CHANGE_PASSWORD_SUCCESS';
export const AUTH_CHANGE_PASSWORD_FAIL = 'AUTH_CHANGE_PASSWORD_FAIL';

export const GET_ENTITIES_START = 'GET_ENTITIES_START';
export const GET_ENTITIES_SUCCESS = 'GET_ENTITIES_SUCCESS';
export const GET_ENTITIES_FAIL = 'GET_ENTITIES_FAIL';